### ISSUE TITLE
permissions and code

### ISSUE THREAD

**Issue by Vaibhavtamakuwala** [knovator/masters-node#25]
Hii, 

I am using this package and facing some issues which i am mentioning here.
1. not getting any permission to change or add master.
2. code should be unique. We can create duplicate data with same code now.

**Comment by chavda-bhavik** [comment]
Hey @Vaibhavtamakuwala Thanks for reporting issue. We solved this issue, you can install the latest version of `@knovator/masters-node` and it will solve your issue.
